ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        # sslPort = 8443
        port: 8082

jwt:
    issuer: "http://0.0.0.0:8082"
    domain: "http://0.0.0.0:8082"
    audience: "users"
    realm: "educo-server"
